// src/Projects.tsx
import { useState } from "react";
import css from "./Projects.module.css";
import { AnimatePresence, motion } from "motion/react";
import { getAllImageLinksInAssetDirectory } from "./utils/files";
import clsx from "clsx";
const featuredProjects = [
  {
    name: "CMU Courses",
    assetFolder: "cmu-courses",
    description: `CMU Courses is a course browser built by and for CMU students.
          Bringing together course information, schedules and FCE data, it makes
          it possible for CMU students to plan their semesters and browse for
          courses. lmao what is this description`,
    link: "https://www.cmucourses.com/",
  },
  {
    name: "CMU Eats",
    assetFolder: "cmu-eats",
    description:
      "CMUEats is your one-stop-shop for finding out what campus dining locations are open right now.",
    link: "https://cmueats.com/",
  },
  {
    name: "CMU Maps",
    assetFolder: "cmu-maps",
    description: "Providing indoor maps and navigation for the CMU campus.",
    link: "https://cmumaps.com/",
  },
];

export default function Projects() {
  const [selectedProjectIndex, setSelectedProjectIndex] = useState(0);
  const designIcons = getAllImageLinksInAssetDirectory("design-app-icons");
  const codeIcons = getAllImageLinksInAssetDirectory("code-app-icons");
  return (
    <section className="centered-section">
      <div className={css["title-section"]}>
        <h1 className={css["title-section__header"]}>
          From{" "}
          <span className={css["design-text-container"]}>
            Design
            <div className={css["decoration"]}>
              <div className={css["decoration__line"]} />
              <div className={css["decoration__line"]} />
              <div className={css["decoration__line"]} />
              <div className={css["decoration__line"]} />
              <div className={css["decoration__square"]} />
              <div className={css["decoration__square"]} />
              <div className={css["decoration__square"]} />
              <div className={css["decoration__square"]} />
            </div>
          </span>{" "}
          to{" "}
          <span className={css["title-section__header__code-block"]}>
            {"<"}
          </span>
          Development
          <span className={css["title-section__header__code-block"]}>
            {"/>"}
          </span>
        </h1>
        <p className={css["title-section__desc"]}>
          We bring to life a variety of tech services geared towards improving
          the CMU campus experience and inspiring the community!˙
        </p>
        <div>
          {designIcons.slice(0, 4).map((icon) => (
            <motion.img
              drag
              dragSnapToOrigin
              className={clsx(
                css["tool-logo-slot"],
                icon.includes("/ai") && css["tool-logo-slot--ai-san"]
              )}
              src={icon}
              alt=""
              key={icon}
            />
          ))}
          {codeIcons.slice(0, 4).map((icon) => (
            <motion.img
              drag
              dragSnapToOrigin
              className={css["tool-logo-slot"]}
              src={icon}
              alt=""
              key={icon}
            />
          ))}
          <div className={css["tool-logo-slot"]} />
          <div className={css["tool-logo-slot"]} />
          <div className={css["tool-logo-slot"]} />
          <div className={css["tool-logo-slot"]} />
          <div className={css["tool-logo-slot"]} />
          <div className={css["tool-logo-slot"]} />
          <div className={css["tool-logo-slot"]} />
          <div className={css["tool-logo-slot"]} />
        </div>
      </div>
      <ul className={css["project-tabs"]} role="tablist">
        {featuredProjects.map(({ name, assetFolder }, i) => {
          return (
            <button
              className={css["tab"]}
              role="tab"
              aria-selected={i === selectedProjectIndex ? "true" : "false"}
              onClick={() => setSelectedProjectIndex(i)}
              key={assetFolder}
            >
              <img
                className={css["tab__image"]}
                src={
                  new URL(
                    `./assets/projects/${assetFolder}/icon.png`,
                    import.meta.url
                  ).href
                }
                alt=""
              />
              <div className={css["tab__name"]}>{name}</div>
            </button>
          );
        })}
        <button className={css["tab"]}>
          <img
            className={css["tab__image"]}
            src={new URL("./assets/icons/go-to-icon.svg", import.meta.url).href}
            alt=""
            style={{ height: "1em" }}
          />
          <div className={css["tab__name"]}>See more</div>
        </button>
      </ul>
      <div className={css["panel-container"]}>
        <AnimatePresence>
          <motion.div
            className={css["panel"]}
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            key={selectedProjectIndex}
          >
            <a
              href={featuredProjects[selectedProjectIndex].link}
              target="_blank"
            >
              <img
                className={css["panel__img"]}
                src={
                  new URL(
                    `./assets/projects/${featuredProjects[selectedProjectIndex].assetFolder}/main.png`,
                    import.meta.url
                  ).href
                }
                alt=""
              />
            </a>
            <div className={css["panel__footer"]}>
              {featuredProjects[selectedProjectIndex].description}
            </div>
          </motion.div>
        </AnimatePresence>
      </div>
    </section>
  );
}

// apps/web/src/routes/(main)/projects/+page.svelte
<script lang="ts">
  import { Header } from '$lib/sections/projects/Header.svelte';
  import ProjectPanel from '$lib/sections/projects/ProjectPanel.svelte';
  import {
    BocchiIcon,
    CSSIcon,
    JavascriptIcon,
    MongoDBIcon,
    NextJSIcon,
    ReactIcon,
    TailwindIcon,
    TypescriptIcon,
    ViteIcon,
    PostgresIcon
  } from '$lib/sections/projects/icons';
  import { getAllImageLinksInAssetDirectory } from '$lib/utils/files';
</script>

<Header />
<ProjectPanel
  repoIds={[461300766]}
  description="Bringing together course information, schedules and FCE data, it makes it possible for CMU students to plan their semesters and browse for courses."
  imageURLs={getAllImageLinksInAssetDirectory('cmu-courses')}
  technologiesUsed={[
    JavascriptIcon,
    TypescriptIcon,
    ReactIcon,
    NextJSIcon,
    TailwindIcon,
    MongoDBIcon
  ]}
  name="CMU Courses"
  url="https://cmucourses.com/"
/>
<ProjectPanel
  repoIds={[461295694, 28149130]}
  description="CMUEats is your one-stop-shop for finding out what campus dining locations are open right now."
  imageURLs={getAllImageLinksInAssetDirectory('cmu-eats')}
  technologiesUsed={[TypescriptIcon, ReactIcon, CSSIcon, ViteIcon, BocchiIcon]}
  name="CMU Eats"
  url="https://cmueats.com/"
/>
<ProjectPanel
  repoIds={[
    907552548, 314884445, 412883321, 910847128, 941314467, 983636067,
    1005207710, 1008068854, 511749350, 606940704, 801739296, 819120359,
    847150918
  ]}
  description="CMUMaps combines indoor and outdoor maps and navigation so that you will never get lost again on campus."
  imageURLs={getAllImageLinksInAssetDirectory('cmu-maps')}
  technologiesUsed={[TypescriptIcon, ReactIcon, ViteIcon, TailwindIcon, PostgresIcon]}
  name="CMU Maps"
  url="https://cmumaps.com/"
/>
<ProjectPanel
  repoIds={[561467360, 308943713, 295896072]}
  description="Lost and found is the official lost and found service for the Cohon University Center!  We help reunite lost items with their owners."
  imageURLs={getAllImageLinksInAssetDirectory('lost-and-found')}
  technologiesUsed={[TypescriptIcon, ReactIcon, NextJSIcon, TailwindIcon, PostgresIcon]}
  name="Lost and Found"
  url="https://lostandfound.andrew.cmu.edu"
/>
<div style="height: 150px;"></div>
