// apps/web/src/lib/sections/home/Header.svelte
<script lang="ts">
  import { page } from '$app/stores';
  import css from './Header.module.css';
  import scottylabsLogo from '$lib/assets/scottylabs-logo.svg';
  import teamIcon from '$lib/assets/icons/team.svg';
  import projectsIcon from '$lib/assets/icons/projects.svg';
  import sponsorsIcon from '$lib/assets/icons/sponsors.svg';

  const navLinks = [
    {
      icon: projectsIcon,
      url: '/projects',
      text: 'Projects'
    },
    {
      icon: teamIcon,
      url: '/team',
      text: 'Team'
    },
    {
      icon: sponsorsIcon,
      url: '/sponsors',
      text: 'Sponsors'
    }
  ];

  $: currentPath = $page.url.pathname;
</script>

<header class={css['main-header-container']}>
  <div class={css['main-header-layout']}>
    <a
      class={css.logo}
      href="/"
      data-sveltekit-preload-data="hover"
    >
      <img class={css['logo__img']} src={scottylabsLogo} alt="ScottyLabs" />
      <div class={css['logo__text']}>ScottyLabs</div>
    </a>
    <nav class={css['main-nav']}>
      {#each navLinks as link (link.url)}
        <a
          class={`${css['nav-button']} ${currentPath === link.url ? css['nav-button--active'] : ''}`.trim()}
          href={link.url}
          data-sveltekit-preload-data="hover"
        >
          <img class={css['nav-button__icon']} src={link.icon} alt="" />
          <div class={css['nav-button__text']}>{link.text}</div>
        </a>
      {/each}
    </nav>
  </div>
</header>

// src/Header.tsx
import css from "./Header.module.css";
import clsx from "clsx";

import scottylabsLogo from "./assets/scottylabs-logo.svg";
import aboutIcon from "./assets/icons/about.svg";
import teamIcon from "./assets/icons/team.svg";
import projectsIcon from "./assets/icons/projects.svg";
import eventsIcon from "./assets/icons/events.svg";
import sponsorsIcon from "./assets/icons/sponsors.svg";
const navLinks = [
  {
    icon: aboutIcon,
    url: "/about",
    text: "About",
  },
  {
    icon: teamIcon,
    url: "/team",
    text: "Team",
  },
  {
    icon: projectsIcon,
    url: "/projects",
    text: "Projects",
  },
  {
    icon: eventsIcon,
    url: "/events",
    text: "Events",
  },
  {
    icon: sponsorsIcon,
    url: "/sponsors",
    text: "Sponsors",
  },
];
function Header() {
  return (
    <header className={css["main-header"]}>
      <div className={css["logo"]}>
        <img className={css["logo__img"]} src={scottylabsLogo} />

        <div className={css["logo__text"]}>ScottyLabs</div>
      </div>
      <nav className={css["main-nav"]}>
        {navLinks.map(({ icon, url, text }) => (
          <a aria-current={url === "/about"}>
            <button
              className={clsx(
                css["nav-button"],
                url === "/about" && css["nav-button--active"]
              )}
            >
              <img className={css["nav-button__icon"]} src={icon} />
              <div className={css["nav-button__text"]}>{text}</div>
            </button>
          </a>
        ))}
      </nav>
    </header>
  );
}

export default Header;
