// apps/web/src/lib/sections/home/Header.svelte
<script lang="ts">
  import { page } from '$app/stores';
  import css from './Header.module.css';
  import scottylabsLogo from '$lib/assets/scottylabs-logo.svg';
  import teamIcon from '$lib/assets/icons/team.svg';
  import projectsIcon from '$lib/assets/icons/projects.svg';
  import sponsorsIcon from '$lib/assets/icons/sponsors.svg';

  const navLinks = [
    {
      icon: projectsIcon,
      url: '/projects',
      text: 'Projects'
    },
    {
      icon: teamIcon,
      url: '/team',
      text: 'Team'
    },
    {
      icon: sponsorsIcon,
      url: '/sponsors',
      text: 'Sponsors'
    }
  ];

  $: currentPath = $page.url.pathname;
</script>

<header class={css['main-header-container']}>
  <div class={css['main-header-layout']}>
    <a
      class={css.logo}
      href="/"
      data-sveltekit-preload-data="hover"
    >
      <img class={css['logo__img']} src={scottylabsLogo} alt="ScottyLabs" />
      <div class={css['logo__text']}>ScottyLabs</div>
    </a>
    <nav class={css['main-nav']}>
      {#each navLinks as link (link.url)}
        <a
          class={`${css['nav-button']} ${currentPath === link.url ? css['nav-button--active'] : ''}`.trim()}
          href={link.url}
          data-sveltekit-preload-data="hover"
        >
          <img class={css['nav-button__icon']} src={link.icon} alt="" />
          <div class={css['nav-button__text']}>{link.text}</div>
        </a>
      {/each}
    </nav>
  </div>
</header>

// apps/web/app/sections/home/Header.tsx
import css from "./Header.module.css";
import clsx from "clsx";

import scottylabsLogo from "../../assets/scottylabs-logo.svg";
import teamIcon from "../../assets/icons/team.svg";
import projectsIcon from "../../assets/icons/projects.svg";
import eventsIcon from "../../assets/icons/events.svg";
import sponsorsIcon from "../../assets/icons/sponsors.svg";
import { NavLink, useLocation } from "react-router";
const navLinks = [
  {
    icon: projectsIcon,
    url: "/projects",
    text: "Projects",
  },
  {
    icon: teamIcon,
    url: "/team",
    text: "Team",
  },
  {
    icon: sponsorsIcon,
    url: "/sponsors",
    text: "Sponsors",
  },
];
function Header() {
  return (
    <header className={css["main-header-container"]}>
      <div className={css["main-header-layout"]}>
        <NavLink
          className={css["logo"]}
          to={"/"}
          // onClick={() =>
          //   window.scrollTo({
          //     top: 0,
          //     left: 0,
          //     behavior: "smooth",
          //   })
          // }
          prefetch="intent"
        >
          <img className={css["logo__img"]} src={scottylabsLogo} />

          <div className={css["logo__text"]}>ScottyLabs</div>
        </NavLink>
        <nav className={css["main-nav"]}>
          {navLinks.map(({ icon, url, text }) => (
            <NavLink
              className={({ isActive }) =>
                clsx(css["nav-button"], isActive && css["nav-button--active"])
              }
              to={url}
              prefetch="intent"
              key={url}
            >
              <img className={css["nav-button__icon"]} src={icon} />
              <div className={css["nav-button__text"]}>{text}</div>
            </NavLink>
          ))}
          <a
            className={css["events-button"]}
            href="https://invite.scottylabs.org"
          >
            <img className={css["events-button__icon"]} src={eventsIcon} />
            <div>Events</div>
          </a>
        </nav>
      </div>
    </header>
  );
}

export default Header;
